apiVersion: apps/v1
kind: Deployment
metadata:
  name: drttytd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drttytd
  template:
    metadata:
      labels:
        app: drttytd
    spec:
      containers:
      - image: okteto.dev/drttytd:latest
        name: drttytd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "97d5fc8c-fe25-456a-a2ed-4432eb2977bf"
        - name: Vless_Path
          value: "/ftftrsytfuyguysd"
        - name: Vmess_UUID
          value: "97d5fc8c-fe25-456a-a2ed-4432eb2977bf"
        - name: Vmess_Path
          value: "/sresrytxgfkjgyv"
        - name: Share_Path
          value: "/v2link"
